import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import { Toaster } from "sonner";
import { AuthProvider, useAuth } from "./(auth)/Context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>

        <Toaster
          theme="dark"
          position="top-center"
          expand={false}
          richColors={false}
          toastOptions={{
            style: {
              background: "#0d0d0d",
              border: "1px solid rgba(249, 115, 22, 0.2)",
              color: "#fafafa",
              borderRadius: "1.5rem",
              padding: "16px",
              fontSize: "12px",
              fontWeight: "700",
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              boxShadow: "0 20px 40px rgba(0,0,0,0.4)",
            },
          }}
        />
      </body>
    </html>
  );
}
